#!/usr/bin/env bash
set -euo pipefail
source /etc/katsu/lib/core.sh
source /etc/katsu/lib/ui.sh
ssh_add(){ load_cfg; read -rp "Username: " user; valid_user "$user" || { echo "Username tidak valid"; pause; return; }; read -rp "Expired berapa hari: " days; read -rp "Limit IP [2]: " iplimit; iplimit="${iplimit:-2}"; pass="$(tr -dc A-Za-z0-9 </dev/urandom | head -c 8)"; useradd -e "$(date -d "+$days days" +%F)" -s /bin/false -M "$user"; echo "$user:$pass" | chpasswd; exp="$(date -d "+$days days" +%F)"; save_user_json ssh "$user" "$pass" "$exp" "$iplimit"; dashboard; box "SSH ACCOUNT"; printf " Username      : %s\n Password      : %s\n Domain        : %s\n Port          : 22\n Expired       : %s\n Limit IP      : %s\n" "$user" "$pass" "$DOMAIN" "$exp" "$iplimit"; pause; }
ssh_del(){ read -rp "Username: " user; userdel "$user" 2>/dev/null || true; rm -f "$USERS_DIR/ssh/$user.json"; echo "Deleted: $user"; pause; }
ssh_trial(){ user="trial$(tr -dc a-z0-9 </dev/urandom | head -c 4)"; pass="$(tr -dc A-Za-z0-9 </dev/urandom | head -c 8)"; exp="$(date -d '+1 day' +%F)"; useradd -e "$exp" -s /bin/false -M "$user"; echo "$user:$pass" | chpasswd; save_user_json ssh "$user" "$pass" "$exp" 1; echo "Trial SSH dibuat: $user / $pass"; pause; }
ssh_renew(){ read -rp "Username: " user; read -rp "Tambah hari: " days; file="$USERS_DIR/ssh/$user.json"; [ -f "$file" ] || { echo "User tidak ada"; pause; return; }; old="$(jq -r .expired "$file")"; new="$(date -d "$old +$days days" +%F 2>/dev/null || date -d "+$days days" +%F)"; chage -E "$new" "$user" || true; jq --arg d "$new" '.expired=$d' "$file" > "$file.tmp" && mv "$file.tmp" "$file"; echo "Expired baru: $new"; pause; }
ssh_list(){ dashboard; box "SSH USER LIST"; for u in $(list_users ssh); do exp="$(jq -r .expired "$USERS_DIR/ssh/$u.json")"; iplimit="$(jq -r .iplimit "$USERS_DIR/ssh/$u.json")"; status="$(jq -r .status "$USERS_DIR/ssh/$u.json")"; printf " %-18s exp:%-12s iplimit:%-3s status:%s\n" "$u" "$exp" "$iplimit" "$status"; done; pause; }
ssh_limit(){ read -rp "Username: " user; read -rp "Limit IP baru: " limit; file="$USERS_DIR/ssh/$user.json"; [ -f "$file" ] || { echo "User tidak ada"; pause; return; }; jq --argjson l "$limit" '.iplimit=$l' "$file" > "$file.tmp" && mv "$file.tmp" "$file"; echo "Updated"; pause; }
ssh_online(){ dashboard; box "SSH ONLINE USER"; /usr/local/bin/katsu-ssh-online 2>/dev/null || who | awk '{print $1,$5}' | sort | uniq; pause; }
